@ECHO OFF&&SETLOCAL ENABLEDELAYEDEXPANSION&&CD /D %~DP0
Reg.exe query "HKU\S-1-5-19\Environment">NUL
IF NOT %ERRORLEVEL% EQU 0 ECHO Right-Click ^& Run As Administrator&&PAUSE&&EXIT 0
SET "PROG_SOURCE=%CD%"&&SET "PROG_TARGET=%CD%"&&SET "IMAGE_FOLDER=%CD%"
:FILEMGR_START
@ECHO OFF&&CLS&&TITLE  Download from github.com/joshuacline&&COLOR 06&&CALL:PAD_LINE&&ECHO                  Josh's File Manager Command-Wrapper&&CALL:PAD_LINE
IF NOT DEFINED FILEMGR_SOURCE SET "FILEMGR_SOURCE=%PROG_SOURCE%"&&SET "FILEMGR_TARGET=%PROG_TARGET%"
ECHO  [SOURCE[%FILEMGR_SOURCE%] [TARGET[%FILEMGR_TARGET%]&&CALL:PAD_LINE&&ECHO   CURRENTLY IN [%FILEMGR_SOURCE%]:
IF DEFINED PROG_OPER SET LIST_FMT=NUMERAL&&SET "LIST_DIR=%FILEMGR_SOURCE%\*.*"&&ECHO.&&CALL:FILE_LIST&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER SET LIST_FMT=PLAIN&&SET "LIST_DIR=%FILEMGR_SOURCE%\*.*"&&ECHO.&&CALL:FILE_LIST&&CALL:PAD_LINE
IF NOT DEFINED PROG_OPER ECHO     {O}pen  {C}opy  {M}ove  {D}upe  {R}Rename  {Z}Delete  {N}ew&&CALL:PAD_LINE&&ECHO    {X}plore {S}wap-SRC/TGT {T}arget-Set   {#}TakeOwn {*}SymLink&&CALL:PAD_LINE
IF DEFINED PROG_OPER ECHO                  Enter File # To [%PROG_OPER%] {/}Type&&CALL:PAD_LINE
ECHO                Press (Enter) to Return to Previous Menu
CALL:MENU_SELECT&&IF DEFINED PROG_OPER CALL:FILE_LIST>NUL
IF DEFINED PROG_OPER IF NOT DEFINED SELECT SET PROG_OPER=
IF DEFINED SELECT CALL:FILEMGR_FINISH
GOTO:FILEMGR_START
:FILEMGR_FINISH
IF "%PROG_SOURCE%\%SELECT%"=="%PROG_SOURCE%\" EXIT /B
IF "%SELECT%"=="." SET PROG_OPER=FOLDER_DOWN
IF "%SELECT%"==".." SET PROG_OPER=FOLDER_UP
IF "%SELECT%"=="C" SET PROG_OPER=FILEMGR_COPY&&EXIT /B
IF "%SELECT%"=="D" SET PROG_OPER=FILEMGR_DUPE&&EXIT /B
IF "%SELECT%"=="O" SET PROG_OPER=FILEMGR_OPEN&&EXIT /B
IF "%SELECT%"=="M" SET PROG_OPER=FILEMGR_MOVE&&EXIT /B
IF "%SELECT%"=="N" SET PROG_OPER=FILEMGR_NEW
IF "%SELECT%"=="X" SET PROG_OPER=FILEMGR_EXPLORE
IF "%SELECT%"=="R" SET PROG_OPER=FILEMGR_RENAME&&EXIT /B
IF "%SELECT%"=="S" CALL:FILEMGR_SWAP&&EXIT /B
IF "%SELECT%"=="T" SET PROG_OPER=TGT_SET
IF "%SELECT%"=="*" SET PROG_OPER=FILEMGR_SYMLINK&&EXIT /B
IF "%SELECT%"=="#" SET PROG_OPER=FILEMGR_TAKEOWN&&EXIT /B
IF "%SELECT%"=="Z" SET PROG_OPER=FILEMGR_DELETE&&EXIT /B
REM FIXES GLITCH IF FILE OR FOLDER NAMED "C,D,O,M,R,Z". NEEDS TO BE 1ST
FOR %%a in (C D O M R Z #) DO (IF DEFINED PROG_OPER IF "%SELECT%"=="%%a" EXIT /B)
REM FIXES GLITCH IF FILE OR FOLDER NAMED "C,D,O,M,R,Z". NEEDS TO BE 1ST
IF "%PROG_OPER%"=="FILEMGR_DUPE" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_SYMLINK" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_TAKEOWN" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="ASSIGN_MACRO" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_COPY" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_DELETE" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_MOVE" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_OPEN" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_RENAME" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%" EXIT /B
IF "%PROG_OPER%"=="FILEMGR_SYMLINK" IF "%FILEMGR_SOURCE%"=="%FILEMGR_TARGET%" ECHO SOURCE/TARGET ARE THE SAME..&&SET PROG_OPER=&&PAUSE&&EXIT /B
IF "%PROG_OPER%"=="FILEMGR_COPY" IF "%FILEMGR_SOURCE%"=="%FILEMGR_TARGET%" ECHO SOURCE/TARGET ARE THE SAME..&&SET PROG_OPER=&&PAUSE&&EXIT /B
IF "%PROG_OPER%"=="FILEMGR_MOVE" IF "%FILEMGR_SOURCE%"=="%FILEMGR_TARGET%" ECHO SOURCE/TARGET ARE THE SAME..&&SET PROG_OPER=&&PAUSE&&EXIT /B
IF "%PROG_OPER%"=="FILEMGR_EXPLORE" ECHO.ENTER ANY PATH&&ECHO (CANNOT END IN "\")&&FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (IF EXIST "%%G:\" ECHO [%%G:])
IF "%PROG_OPER%"=="FILEMGR_EXPLORE" CALL:MENU_SELECT
IF "%PROG_OPER%"=="FILEMGR_EXPLORE" IF EXIST "%SELECT%\" SET "FILEMGR_SOURCE=%SELECT%"
IF "%PROG_OPER%"=="FILEMGR_TAKEOWN" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" TAKEOWN /F "%FILEMGR_SOURCE%\%SELECT%" /R /D Y
IF "%PROG_OPER%"=="FILEMGR_TAKEOWN" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" ICACLS "%FILEMGR_SOURCE%\%SELECT%\*" /grant %USERNAME%:F /T >NUL 2>&1
IF "%PROG_OPER%"=="FILEMGR_TAKEOWN" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" PAUSE
IF "%PROG_OPER%"=="FILEMGR_TAKEOWN" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" TAKEOWN /F "%FILEMGR_SOURCE%\%SELECT%"
IF "%PROG_OPER%"=="FILEMGR_TAKEOWN" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" ICACLS "%FILEMGR_SOURCE%\%SELECT%" /grant %USERNAME%:F >NUL 2>&1
IF "%PROG_OPER%"=="FILEMGR_TAKEOWN" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" PAUSE
IF "%PROG_OPER%"=="FILEMGR_SYMLINK" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" MKLINK /J "%FILEMGR_TARGET%\%SELECT%" "%FILEMGR_SOURCE%\%SELECT%"&&PAUSE
IF "%PROG_OPER%"=="FILEMGR_SYMLINK" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" MKLINK "%FILEMGR_TARGET%\%SELECT%" "%FILEMGR_SOURCE%\%SELECT%"&&PAUSE
IF "%PROG_OPER%"=="FOLDER_DOWN" CALL SET "FILEMGR_SOURCE=%%FILEMGR_SOURCE_%FILEMGR_SOURCE_#%%%"&&CALL SET /A FILEMGR_SOURCE_#+=1
IF "%PROG_OPER%"=="FOLDER_UP" CALL SET "FILEMGR_SOURCE=%%FILEMGR_SOURCE_%FILEMGR_SOURCE_#%%%"&&CALL SET /A FILEMGR_SOURCE_#-=1
IF "%PROG_OPER%"=="FILEMGR_DELETE" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" DEL /Q /F "\\?\%FILEMGR_SOURCE%\%SELECT%"
IF "%PROG_OPER%"=="FILEMGR_DELETE" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" RD /S /Q "\\?\%FILEMGR_SOURCE%\%SELECT%">NUL 2>&1
IF "%PROG_OPER%"=="FILEMGR_OPEN" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" "%FILEMGR_SOURCE%\%SELECT%"
IF "%PROG_OPER%"=="FILEMGR_OPEN" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" SET "FILEMGR_LAST=%FILEMGR_SOURCE%"&&CALL SET /A FILEMGR_SOURCE_#+=1&&CALL SET "FILEMGR_SOURCE_%FILEMGR_SOURCE_#%=%FILEMGR_SOURCE%"&&CALL SET "FILEMGR_SOURCE=%FILEMGR_SOURCE%\%SELECT%"
IF "%PROG_OPER%"=="FILEMGR_COPY" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" XCOPY "%FILEMGR_SOURCE%\%SELECT%" "%FILEMGR_TARGET%\" /C /Y
IF "%PROG_OPER%"=="FILEMGR_COPY" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" XCOPY "%FILEMGR_SOURCE%\%SELECT%" "%FILEMGR_TARGET%\%SELECT%\" /E /C /I /Y
IF "%PROG_OPER%"=="FILEMGR_DUPE" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" XCOPY "%FILEMGR_SOURCE%\%SELECT%" "%FILEMGR_SOURCE%\Copy_%SELECT%\" /C /Y
IF "%PROG_OPER%"=="FILEMGR_DUPE" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" XCOPY "%FILEMGR_SOURCE%\%SELECT%" "%FILEMGR_SOURCE%\Copy_%SELECT%\" /E /C /I /Y
IF "%PROG_OPER%"=="FILEMGR_MOVE" IF NOT EXIST "%FILEMGR_SOURCE%\%SELECT%\*" MOVE /Y "%FILEMGR_SOURCE%\%SELECT%" "%FILEMGR_TARGET%\"
IF "%PROG_OPER%"=="FILEMGR_MOVE" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" XCOPY "%FILEMGR_SOURCE%\%SELECT%" "%FILEMGR_TARGET%\%SELECT%\" /E /C /I /Y
IF "%PROG_OPER%"=="FILEMGR_MOVE" IF EXIST "%FILEMGR_SOURCE%\%SELECT%\*" RD /S /Q "\\?\%FILEMGR_SOURCE%\%SELECT%">NUL 2>&1
IF "%PROG_OPER%"=="FILEMGR_NEW" ECHO. {1}Folder&&ECHO. {2}File&&CALL:MENU_SELECT
IF "%PROG_OPER%"=="FILEMGR_NEW" IF "%SELECT%"=="1" CALL SET NEW_TYPE=FOLDER&&ECHO. New FOLDER Name?&&SET SELECT=&&SET /P "SELECT=$>>"
IF "%PROG_OPER%"=="FILEMGR_NEW" IF "%NEW_TYPE%"=="FOLDER" SET NEW_TYPE=&&MD "%FILEMGR_SOURCE%\%SELECT%">NUL 2>&1
IF "%PROG_OPER%"=="FILEMGR_NEW" IF "%SELECT%"=="2" CALL SET NEW_TYPE=FILE&&ECHO. New FILE Name?&&SET SELECT=&&SET /P "SELECT=$>>"
IF "%PROG_OPER%"=="FILEMGR_NEW" IF "%NEW_TYPE%"=="FILE" SET NEW_TYPE=&&ECHO.>"%FILEMGR_SOURCE%\%SELECT%"
IF "%PROG_OPER%"=="FILEMGR_RENAME" SET OLD_NAME=%SELECT%&&ECHO.&&ECHO NEW NAME?&&SET NEW_NAME=&&SET /P "NEW_NAME=$>>"
IF "%PROG_OPER%"=="FILEMGR_RENAME" IF DEFINED NEW_NAME REN "%FILEMGR_SOURCE%\%OLD_NAME%" "%NEW_NAME%">NUL 2>&1
IF "%PROG_OPER%"=="TGT_SET" SET "FILEMGR_TARGET=%FILEMGR_SOURCE%"
IF DEFINED PROG_OPER SET PROG_OPER=
EXIT /B
:FILEMGR_SWAP
IF NOT EXIST "%FILEMGR_SOURCE%" EXIT /B
IF NOT EXIST "%FILEMGR_TARGET%" EXIT /B
SET FILEMGR_SOURCE_TMP=%FILEMGR_SOURCE%&&SET FILEMGR_TARGET_TMP=%FILEMGR_TARGET%
SET FILEMGR_SOURCE=%FILEMGR_TARGET_TMP%&&SET FILEMGR_TARGET=%FILEMGR_SOURCE_TMP%
EXIT /B
:PAD_LINE
ECHO ====================================================================
EXIT /B
:MENU_SELECT
SET SELECT=&&SET /P "SELECT=$>>"&&FOR %%G in (A B C D E F G H I J K L M N O P Q R S T U V W X Y Z) DO (CALL SET "SELECT=%%SELECT:%%G=%%G%%")
EXIT /B
:FILE_LIST
IF DEFINED LIST_DIR IF EXIST "%LIST_DIR%" SET LIST_CNT=0&&DIR "%LIST_DIR%" /A: /B /O:GN>%TEMP%\$HZ.TXT&&FOR /F "TOKENS=*" %%a in (%TEMP%\$HZ.TXT) DO (CALL SET /A LIST_CNT+=1&&CALL SET "OBJ_NAME=%%a"&&CALL:FILE_LIST_OUTSIDE)
IF DEFINED LIST_DIR IF NOT EXIST "%LIST_DIR%" ECHO  [CRICKETS..]
ECHO.&&SET LIST_DIR=&&SET LIST_TXT=&&SET LIST_FMT=&&SET FILE_LIST_EXT=&&IF EXIST "%TEMP%\$HZ.TXT" DEL /F "%TEMP%\$HZ.TXT">NUL 2>&1
IF "%SELECT%"=="\" CALL:MENU_SELECT&&EXIT /B
IF "%SELECT%"=="/" CALL:MENU_SELECT&&EXIT /B
CALL SET "SELECT=%%TEMP_NAME%SELECT%%%"
CALL SET "LIST_OUTPUT=%%TEMP_NAME%SELECT%%%"
EXIT /B
:FILE_LIST_OUTSIDE
CALL SET "TEMP_NAME%LIST_CNT%=%OBJ_NAME%"
IF "%LIST_FMT%"=="NUMERAL" ECHO  [ %LIST_CNT% ]\[%OBJ_NAME%]
IF "%LIST_FMT%"=="PLAIN" ECHO  [SRC]\[%OBJ_NAME%]
EXIT /B